local delve = {
    prompts = {
        "frustrated",
        "annoyed",
        "mad",
        "angry",
        "stressed",
        "complain",
        "bruh",
        "listen",
        "unbelievable",
        "ridiculous",
        "upset",
        "tell",
        "explain",
        "talk",
        "bothered",
        "annoying",
        "issue",
        "problem",
        "pain",
        "ugh",
        "fuming",
        "done",
        "over it",
        "can't",
        "why",
        "bro",
        "girl",
        "omg",
        "wtf",
        "seriously",
        "deadass",
        "nah",
        "him",
        "his",
        "her"
    },
    responses = {
        "I hear you.",
        "I’m listening.",
        "Tell me more.",
        "What happened?",
        "Go on...",
        "I got you.",
        "Oh no, what happened?",
        "Sounds tough.",
        "I’m here for you.",
        "I’m all ears.",
        "I’m with you.",
        "Go ahead, I’m listening.",
        "I’m right here.",
        "Tell me everything.",
        "What’s on your mind?",
        "I’m paying attention.",
        "I’m following you.",
        "Keep going, I’m here.",
        "I hear you loud and clear."
    },
    type = "delve"
}

return delve

