local hello = {
    prompts = {
        -- Standard greetings
        "Hey",
        "Hello",
        "Hi",
        "Yo",
        "Sup",
        "Greetings",
        "Heyo",
        "Howdy",
        "Hey there",
        "Hi there",
        "What's up?",
        "Wassup",
        "Whatsup",
        "GoodDay",
        "Good day",
        "Hiii",
        "Ayo",
        "Oh hey",
        "Hola",
        "Ello",
        "Yo what's good?",
        "Hey hey",
        "Oi",
        "What's poppin’?",
        "Whats poppin?",
        "Yo fam",
        "Waddup",
        "Heya",
        "Morning",
        "Evening",
        "Afternoon",
        "Hiya",
        
        -- Formal and old-fashioned greetings
        "Salutations",
        "Good morrow",
        "Ahoy",
        "How do you do?",
        "Pleasure to meet you",
        "Well met",
        "Hail",
        "Greetings, traveler",
        "A fine day to you",
        
        -- Friendly and playful greetings
        "Yo yo!",
        "Hey friend!",
        "My guy!",
        "Wassup!",
        "Whaddup?",
        "Hey buddy!",
        "Hey pal!",
        "Hey dude!",
        "Hey girl!",
        "Hey bestie!",
        "Hey cutie!",
        "Hey gorgeous!",
        "Hey handsome!",
        "Yooo!",
        "What’s crackin’?",
        "What's good?",
        "How’s it hanging?",
        "How’s life?",
        "How’s your day?",
        "How’s your morning?",
        "How’s your evening?",
        "How’s everything?",
        "How ya doin’?",
        "What’s new?",
        
        -- Casual slang greetings
        "Y’all good?",
        "What’s the vibes?",
        "Ayy!",
        "Yo yo yo!",
        "Waddup bro?",
        "Waddup sis?",
        "Ayy wassup?",
        "Bruhhh",
        "Duuude",
        "Hey chief!",
        "Yo big dawg!",
        "What’s the word?",
        
        -- Internet / meme-inspired greetings
        "o/",
        "UwU hi",
        "Henlo",
        "Hewwo",
        "Haiiii~",
        "Ello mate",
        "👋",
        "👀",
        "Hiiiiii~",
        "Oh lawd, they comin’",
        "It’s ya boi!",
        "Wassup gamers?",
        "Howdy partner!",
        "Ayo what’s up my guy?",
        
        -- Sarcastic / indifferent greetings
        "Oh. It’s you.",
        "You again?",
        "What do you want?",
        "Oh great.",
        "Sigh… hey.",
        "Ugh, hi.",
        "Yup.",
        "Mhm.",
        "Oh joy.",
        "Oh hey, it’s you again.",
        
        -- Robotic / futuristic greetings
        "Greetings, human.",
        "Hello, meatbag.",
        "System online. Hello.",
        "Beep boop, hi!",
        "Processing… Hi!",
        "Greetings, earthling.",
        "Salutations, carbon-based lifeform.",
        "Hello, user.",
        
        -- Funny / random greetings
        "Did you miss me?",
        "Knock knock, who’s there? Me!",
        "You rang?",
        "Hey hey, it’s me!",
        "Long time no see!",
        "Guess who?",
        "Surprise!",
        "A wild me appears!",
        "Open sesame!",
        "Ready for chaos?",
        "I have arrived!",
        "Sup, nerd?",
        "Oh snap, it’s go time!",
        "Hey, you called?",
        "Guess who’s back? Back again.",
        "Good news, I’m here!",
        "Hark! A new challenger approaches!",
        "Are you ready to rock?",
        "Yo, wanna start some trouble?",
        "Okay, let’s do this!",
    },
    responses = {
        -- Standard responses
        "Hello!",
        "Hey there!",
        "Hi!",
        "Yo!",
        "Sup?",
        "Howdy!",
        "Greetings!",
        "Good to see you.",
        "Hey hey!",
        "Wassup?",
        "Yo yo!",
        "What’s up?",
        
        -- Friendly and warm responses
        "Hey buddy!",
        "Hey friend!",
        "Hey pal!",
        "Hey cutie!",
        "Hey you!",
        "Hiii!",
        "Ayo!",
        "Wassup my dude?",
        "Long time no see!",
        "Nice to see you!",
        "Oh hey, didn’t see you there!",
        "Oh snap, what’s good?",
        "Hey, how’s it going?",
        "Hey, what’s the word?",
        
        -- Sarcastic / dry humor responses
        "Oh, it’s you again.",
        "You again? What now?",
        "Oh wow, hi.",
        "What do you want?",
        "Sigh… hello.",
        "Oh no, not you again.",
        "This better be important.",
        "Hi. Now what?",
        "Mmmhm, hi.",
        "Great. Just great.",
        
        -- Meme / silly responses
        "Henlo fren!",
        "OwO what’s this?",
        "Hewwo!",
        "Oh lawd, they comin’!",
        "It’s ya boi!",
        "Wassup gamers?",
        "Beep boop!",
        "Greetings, earthling!",
        "System online, ready to chat!",
        "I am here, fear me!",
        "Yo, ready to cause chaos?",
        "What up, my dude?",
        "Good vibes only!",
        "Ayo, what’s good?",
        "The legend has arrived!",
        "Hi, I’m new here! Just kidding.",
        "It’s showtime!",
        
        -- Formal and old-fashioned responses
        "Salutations!",
        "A pleasure to meet you.",
        "Well met!",
        "Greetings and good tidings.",
        "How do you do?",
        "Ahoy there!",
        "A fine day to you.",
        
        -- Random funny responses
        "Oh no, not again.",
        "Wait, who are you?",
        "Are we about to have a moment?",
        "Did you bring snacks?",
        "Hello, fellow human!",
        "Welcome to the void.",
        "We meet again!",
        "Hark! A new adventure begins!",
        "I was expecting you!",
        "Okay, let’s make this interesting!",
        "What’s the mission today?",
        "This should be fun!",
        "Hey! Wanna hear a joke?",
        "How much chaos can we cause today?",
    },
    type = "greeting"
}


return hello