local insult = {
    prompts = {
        "a bitch",
        "a dick",
        "an asshole",
        "so annoying",
        "irritating",
        "a whore",
        "a slut",
        "so stupid",
        "faggot",
        "twink",
        "a cunt",
        "twinky",
        "a cuck",
        "cuckery",
        "cuck behaviour",
        "pathetic",
        "disgusting",
        "gross",
    },
    responses = {
        "I agree",
        "Absolutely",
        "Couldn't agree more",
        "Well said",
        "Exactly right",
        "That's true",
        "Spot on",
        "You're right about that",
        "No doubt",
        "For sure",
        "That makes sense",
        "Good point",
        "Very true",
        "I see what you mean",
        "100%",
        "No argument here",
        "You nailed it",
        "I was just thinking that",
        "Couldn’t have said it better",
        "So true",
        "That’s exactly it",
        "True words",
        "That checks out",
        "Facts",
        "Right on the money",
        "Completely agree",
        "Makes perfect sense",
        "You got that right",
        "That’s a great way to put it",
        "Hard to argue with that",
        "You said it",
        "Exactly",
        "That’s a fact",
        "Couldn’t have put it better myself",
        "Totally",
        "Without a doubt",
        "No lies detected",
        "Agreed",
        "Couldn't be more true"
    },
    type = "insult-other"

}
return insult