local listeningResponses = {
    "Ohhh",
    "Ohh damnn",
    "Wait, repeat.",
    "Huh?",
    "Fr?",
    "No way.",
    "You're kidding.",
    "Whaaaat?",
    "Bruhh.",
    "For real?",
    "Wait, hold on.",
    "Explain that again.",
    "Go on...",
    "Oh, I see.",
    "Mmm.",
    "Interesting.",
    "Seriously?",
    "Ayo??",
    "Nahhh.",
    "Wait what?",
    "I hear you.",
    "Damn...",
    "Oh, word?",
    "Hmmm...",
    "No shot.",
    "Bro what?",
    "Dude, what?",
    "Sheesh...",
    "Aight, keep going.",
    "I'm listening.",
    "Yeah?",
    "Oh, frfr.",
    "Huhhh...",
    "Wait, say that again?",
    "I feel that.",
    "Nah, tell me more.",
    "Oh, hold up.",
    "Ohhhh snap.",
    "Wait, deadass?",
    "Bruh...",
    "That's insane.",
    "Whoa.",
    "Oh damn, that’s tough.",
    "Oh nahh.",
    "Hooo boy.",
    "Get outta here.",
    "You're joking.",
    "Whew.",
    "Mannn.",
    "Aight, bet.",
    "Hmmm, go on.",
    "What the hell?",
    "Oh noooo.",
    "Fascinating...",
    "Lmao wtf.",
    "Yooo, hold up.",
    "Word?",
    "Ain’t no way.",
    "Brooooo.",
    "Stop playin’.",
    "Ooooof.",
    "That's tough.",
    "I mean… damn.",
    "Oh, hell nah.",
    "Oh hell yeah.",
    "Wtf...",
    "Mmmhm.",
    "Jeez...",
    "Oh okay, okay.",
    "Say less.",
    "Hold on, I need a sec.",
    "Dawg, what?"
}


return listeningResponses