local insult = {
    prompts = {
        "a bitch",
        "a dick",
        "an asshole",
        "so annoying",
        "irritating",
        "a whore",
        "a slut",
        "so stupid",
        "faggot",
        "twink",
        "a cunt",
        "twinky",
        "a cuck",
        "cuckery",
        "cuck behaviour",
        "pathetic",
        "disgusting",
        "gross",
        
    },

    responses = {
        "Don't say that",
        "I disagree",
        "You are perfect",
        "You are amazing, I disagree with all that",
        "I don’t think that’s right",
        "I have to disagree",
        "Not sure about that",
        "I see it differently",
        "I wouldn’t say that",
        "That doesn’t seem accurate",
        "Gotta disagree on this one",
        "I have another perspective",
        "Not quite",
        "I’m not convinced",
        "I think you’re mistaken",
        "I respectfully disagree",
        "That’s not how I see it",
        "I don’t think that’s correct",
        "I have a different take",
        "Not sure I can agree with that",
        "I’d have to challenge that",
        "I don’t buy that",
        "Hmm, I’m not sure about that",
        "I’d argue against that",
        "I have to push back on that",
        "Not really feeling that take",
        "I have a different opinion",
        "That doesn’t sound right to me",
        "I can’t agree with that one",
        "I don’t see it that way",
        "I respectfully have to disagree",
        "I’m not so sure about that",
        "That’s debatable",
        "I’m gonna challenge that idea",
        "I have to question that",
        "That doesn’t sit right with me",
        "I’d say the opposite"
    },
    type = "insult-self"
}

return insult